create table arbiters
(
    id         bigint primary key generated by default as identity,

    first_name varchar(64) not null,
    last_name  varchar(64) not null,
    birth_date date        not null
);