create table if not exists players
(
    id         bigint primary key generated by default as identity,

    first_name varchar(64) not null,
    last_name  varchar(64) not null,
    nickname   varchar(64),
    birth_date date        not null,

    position   varchar(64) not null,
    leg        varchar(16) not null,
    is_captain boolean     not null default false
);