create table player_skills
(
    id           bigint primary key generated by default as identity,
    player_id    bigint not null,

    passing      int    not null ,
    shooting     int    not null ,
    ball_control int    not null ,

    constraint fk_player foreign key (player_id) references players (id)
);