create table teams
(
    id         bigint primary key generated by default as identity,

    title      varchar(64) not null unique,
    captain_id bigint      not null,

    constraint fk_captain foreign key (captain_id) references players (id)
);