create table if not exists games
(
    id              bigint primary key generated by default as identity,

    season_id       bigint not null,
    game_date       date   not null,
    arbiter_id      bigint not null,

    home_team_id    bigint not null,
    away_team_id    bigint not null,

    home_team_goals int  default 0,
    away_team_goals int  default 0,

    yellow_cards    int  default 0,
    red_cards       int  default 0,

    is_finished     bool default false,

    result          varchar,


    constraint fk_arbiter foreign key (arbiter_id) references arbiters (id),
    constraint fk_home_team foreign key (home_team_id) references teams (id),
    constraint fk_away_team foreign key (away_team_id) references teams (id)
);