create table if not exists player_statistics
(
    id           bigint primary key generated by default as identity,

    player_id    bigint not null,
    game_id      bigint not null,

    goals        int  default 0,
    assists      int  default 0,
    yellow_cards int  default 0,
    red_card     bool default false,

    constraint fk_player foreign key (player_id) references players (id),
    constraint fk_game foreign key (game_id) references games (id)

);