create table if not exists captains
(
    id        bigint primary key generated by default as identity,
    team_id   bigint not null,
    player_id bigint not null,

    constraint fk_team foreign key (team_id) references teams (id),
    constraint fk_player foreign key (player_id) references players (id)
);