spring:
  application:
    name: football-test-app

  datasource:
    url: jdbc:postgresql://localhost:5432/football_db
    username: ""
    password: ""

  jpa:
    open-in-view: false
    show-sql: true
#debug: true
