spring:
#  main:
#    banner-mode: off

  application:
    name: football-test-app

  datasource:
    url: jdbc:postgresql://localhost:5432/football_db
    username: "user"
    password: "pass"

  jpa:
    open-in-view: false
    show-sql: true
#debug: true

server:
  port: 8082

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html



logging:
  level:
    root: info