spring:
  application:
    name: football-test-app

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: "user"
    password: "pass"

  jpa:
    open-in-view: false
    show-sql: true
#debug: true

server:
  port: 8082
